make bem prettier
augustinanders/2023_02_13_quiz-app pull request #6
Opened 2023-02-14 17:04 UTC by augustinanders

2023-02-14 20:25 UTC, toshydev requested changes
One issue, rest LGTM! ⚡️

2023-02-14 20:25 UTC, toshydev commented on css/styles.css
> +.Card__hashtag {
I would call this `.Card__hashtag-list-item` or else it looks like it's the parent of `.Card__hashtag-list`.

2023-02-19 10:56 UTC, augustinanders commented on css/styles.css
> +.Card__hashtag {
Thank you, corrected it now

2023-02-19 10:59 UTC, Satttoshi approved these changes
LGTM :rocket:

2023-02-19 11:00 UTC, merged